#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <unity_app_or_unity_bin> <unity_version_label>"
  echo "Example: $0 /Applications/Unity/Hub/Editor/6000.2.10f1/Unity.app 6000.2.10f1"
  exit 1
fi

UNITY_INPUT="$1"
UNITY_VERSION="$2"

if [[ -d "$UNITY_INPUT" && -x "$UNITY_INPUT/Contents/MacOS/Unity" ]]; then
  UNITY_BIN="$UNITY_INPUT/Contents/MacOS/Unity"
elif [[ -x "$UNITY_INPUT" ]]; then
  UNITY_BIN="$UNITY_INPUT"
else
  echo "Unity executable not found: $UNITY_INPUT" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCHEMA_DIR="$REPO_ROOT/plugins/uxml-lsp/schemas"

if [[ ! -f "$SCHEMA_DIR/catalog.xml" ]]; then
  echo "catalog.xml not found: $SCHEMA_DIR/catalog.xml" >&2
  exit 1
fi

TMP_BASE="$(mktemp -d /tmp/uxml-schema-sync.XXXXXX)"
PROJECT_PATH="$TMP_BASE/project"

cleanup() {
  rm -rf "$TMP_BASE"
}
trap cleanup EXIT

"$UNITY_BIN" -batchmode -nographics -createProject "$PROJECT_PATH" -quit -logFile "$TMP_BASE/create.log"

mkdir -p "$PROJECT_PATH/Assets/Editor"
cat > "$PROJECT_PATH/Assets/Editor/UxmlSchemaExport.cs" <<'CS'
using System;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEngine;

public static class UxmlSchemaExport
{
    public static void Export()
    {
        try
        {
            var type = Type.GetType("UnityEditor.UIElements.UxmlSchemaGenerator, UnityEditor.UIElementsModule");
            if (type == null)
                throw new Exception("UnityEditor.UIElements.UxmlSchemaGenerator type not found");

            var flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static;
            var update = type.GetMethods(flags)
                .FirstOrDefault(m => m.Name == "UpdateSchemaFiles");
            if (update == null)
                throw new Exception("UpdateSchemaFiles method not found");

            var parameters = update.GetParameters();
            object[] args = new object[parameters.Length];
            for (int i = 0; i < parameters.Length; i++)
            {
                var p = parameters[i];
                args[i] = p.HasDefaultValue ? p.DefaultValue : (p.ParameterType.IsValueType ? Activator.CreateInstance(p.ParameterType) : null);
            }

            update.Invoke(null, args);
            EditorApplication.Exit(0);
        }
        catch (Exception ex)
        {
            Debug.LogError("UxmlSchemaExport failed: " + ex);
            EditorApplication.Exit(1);
        }
    }
}
CS

set +e
"$UNITY_BIN" -batchmode -nographics -projectPath "$PROJECT_PATH" -executeMethod UxmlSchemaExport.Export -quit -logFile "$TMP_BASE/export.log"
EXIT_CODE=$?
set -e

if [[ $EXIT_CODE -ne 0 ]]; then
  echo "Unity export failed. See: $TMP_BASE/export.log" >&2
  exit $EXIT_CODE
fi

if [[ ! -d "$PROJECT_PATH/UIElementsSchema" ]]; then
  echo "UIElementsSchema directory was not generated" >&2
  echo "See: $TMP_BASE/export.log" >&2
  exit 1
fi

find "$SCHEMA_DIR" -maxdepth 1 -type f -name '*.xsd' -delete
cp -f "$PROJECT_PATH"/UIElementsSchema/*.xsd "$SCHEMA_DIR"/

SYNC_DATE="$(date -u +%Y-%m-%d)"
cat > "$SCHEMA_DIR/UNITY_SCHEMA_SOURCE.md" <<EOF2
# Unity Schema Source

These XSD files are generated by Unity Editor, not hand-written.

- Unity Editor version: \`$UNITY_VERSION\`
- Unity executable: \`$UNITY_BIN\`
- Generation API: \`UnityEditor.UIElements.UxmlSchemaGenerator.UpdateSchemaFiles()\`
- Generated folder in project: \`UIElementsSchema/\`
- Synced at: \`$SYNC_DATE\`

To regenerate with another Unity version:
1. Run this script with your Unity path/version label.
2. Commit updated files under \`plugins/uxml-lsp/schemas/\`.
EOF2

echo "Synced Unity XSDs from $UNITY_VERSION into $SCHEMA_DIR"
